### ISSUE TITLE
Ony Line - The Great Masquerade

### ISSUE THREAD

**Issue by scotty0100** [classicdb/database#119]
Could be SD2 issue also.

Map & Area: Stormwind Keep

How to replicate the bug: die during the event

What happens: if you get aggro and die you should be able to speak to Squire Rowe to restart it but you can't and Windsor's corpse stays outside SW gates.

What should happen: You should be able to speak to Squire Rowe to restart the event

YouTube Video of event which may help: http://www.youtube.com/watch?v=myj4g07wb88

Extra Information: Tried to abandoned it to try to get it again from the squire but he still wouldn't talk to him. Also when Lady Prestor changed into the Onyxia form, it wasn't Onyxia but a small dragonkin caster.

**Comment by cala** [comment]
Thank you for this report.
I think the first part (if you die during the event) should be fixed via SD2 as almost 100% of this quest is handled by SD2.
Regarding the model used, I clearly remember it being a dragonkin caster back in Classic. At that time, you only truly behold the real Onyxia when entering her lair. It was probably changed later in TBC as the video you linked was released in 2007 and shows TBC skills/weapons.

**Comment by cala** [comment]
I had no issue restarting the quest (you have to wait a bit that the event time out). But, there is another more annoying issue: Bolvar can not handle all the adds by himself, while it should. Before bringing SD2 dev into this, I will first look at the creatures stats to see if they are ok.

**Comment by cala** [comment]
Update: HP of spawned creatures are too high in the DB. Bolvar is also missing its armor value. Both will also be fixed in a separate issue, so I'm closing this one.

**Comment by TheTrueAnimal** [comment]
@cala It seems like he still can't handle all the adds. Did you open a separate issue?
